# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
exclude: CHANGELOG.md|^.vscode
ci:
  autofix_commit_msg: |
    chore(pre-commit): auto fixes from pre-commit.com hooks
    for more information, see https://pre-commit.ci
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.2.0
    hooks:
      - id: check-yaml
      - id: check-added-large-files
      - id: check-merge-conflict
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: "v2.6.2"
    hooks:
      - id: prettier
