// const doc = new GoogleSpreadsheet(config.googleSheetID);

// // Initialize Auth - see https://theoephraim.github.io/node-google-spreadsheet/#/getting-started/authentication
// await doc.useServiceAccountAuth({
//   // env var values are copied from service account credentials generated by google
//   // see "Authentication" section in docs for more info
//   client_email: config.googleAccountEmail,
//   private_key: config.googlePrivateKey,
// });

// await doc.loadInfo();
// console.log(doc.title);

// let sheet: GoogleSpreadsheetWorksheet;
// // ty is cool but balls are cooler

// if (doc.sheetCount < 1) {
//   // If there are no sheets present:
//   sheet = await doc.addSheet({
//     // Make a new sheet with the Tank, DPS, and Support header values.
//     headerValues: ["Tank", "DPS", "Support"],
//   });
// } else if (doc.sheetCount == 1) {
//   // If there is already a sheet:
//   const sheets = doc.sheetsByIndex; // Grab the current sheet
//   sheet = sheets[0]; // Put it in `sheet` variable.
// }

setInterval(() => {
  console.log("slay");
}, 1000 * 60); // Function is called every 3 minutes
